"""Pure metric computations."""

from .binning import bin_series
from .burst import (
    align_highres_to_anchors,
    activity_state_kde_peak_frequencies,
    binned_kde_peak_summary,
    build_network_activity_state,
    build_highres_traces,
    build_participation_activity_state,
    build_population_ifr,
    detect_coarse_burst_epochs,
    detect_high_activity_epochs,
    detect_nested_gamma_anchors,
    detect_network_burst_epochs,
    detect_participation_burst_epochs,
    extract_activity_state_ifr,
    interval_membership,
    order_aligned_rate_by_summary,
    order_aligned_rate_by_x,
    refine_participation_burst_anchors,
    summarize_aligned_electrode_rates,
)
from .cofiring import aggregate_cofiring_heatmap, cofiring_proportions, cofiring_vs_distance_by_delay
from .firing_distance import avg_rate_vs_distance, cofiring_avg_vs_distance
from .ifr import calculate_ifr, ifr_peaks, prepare_ifr_timeseries_panel, prepare_ifr_timeseries_panels
from .transfer_entropy import (
    blocks_to_bins,
    build_observation_summary,
    build_signed_target_map,
    build_trigger_summary,
    counts_from_te_states,
    extract_first_stable_ridge,
    fit_speed_with_bootstrap,
    run_discrete_te,
    transfer_entropy_bits_from_counts,
)
from .waves import analyze_eventwise_waves, fit_wave_speed, summarize_wave_peaks

__all__ = [
    "aggregate_cofiring_heatmap",
    "align_highres_to_anchors",
    "activity_state_kde_peak_frequencies",
    "avg_rate_vs_distance",
    "bin_series",
    "binned_kde_peak_summary",
    "blocks_to_bins",
    "build_observation_summary",
    "build_highres_traces",
    "build_network_activity_state",
    "build_participation_activity_state",
    "build_population_ifr",
    "build_signed_target_map",
    "build_trigger_summary",
    "calculate_ifr",
    "cofiring_avg_vs_distance",
    "cofiring_proportions",
    "cofiring_vs_distance_by_delay",
    "analyze_eventwise_waves",
    "counts_from_te_states",
    "detect_coarse_burst_epochs",
    "detect_high_activity_epochs",
    "detect_nested_gamma_anchors",
    "detect_network_burst_epochs",
    "detect_participation_burst_epochs",
    "extract_activity_state_ifr",
    "extract_first_stable_ridge",
    "fit_speed_with_bootstrap",
    "fit_wave_speed",
    "ifr_peaks",
    "interval_membership",
    "order_aligned_rate_by_summary",
    "order_aligned_rate_by_x",
    "prepare_ifr_timeseries_panel",
    "prepare_ifr_timeseries_panels",
    "refine_participation_burst_anchors",
    "run_discrete_te",
    "summarize_aligned_electrode_rates",
    "summarize_wave_peaks",
    "transfer_entropy_bits_from_counts",
]
